apiVersion: eventing.knative.dev/v1alpha1
kind: RabbitmqBrokerConfig
metadata:
  name: my-rabbit-broker-config
spec:
  rabbitmqClusterReference:
    # Configure name if a RabbitMQ Cluster Operator is being used.
    name: hello-world
    namespace: default
    # namespace: knative-eventing
    # Configure connectionSecret if an external RabbitMQ cluster is being used.
    # connectionSecret:
      # name: rabbitmq-secret-credentials
  queueType: quorum
