# Namespace for sample application
apiVersion: v1
kind: Namespace
metadata:
  name: knative-samples
---
# A default broker
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
  name: my-rabbit-broker-kn
  namespace: knative-samples
spec:
  config:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: RabbitmqBrokerConfig
    name: my-rabbit-broker-config
---
# Helloworld-go app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-go
  namespace: knative-samples
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: helloworld-go
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: helloworld-go
          image: dev.local/kevents:latest
          imagePullPolicy: Never
---
# Service that exposes helloworld-go app.
# This will be the subscriber for the Trigger
apiVersion: v1
kind: Service
metadata:
  name: helloworld-go
  namespace: knative-samples
spec:
  selector:
    app: helloworld-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
# Knative Eventing Trigger to trigger the helloworld-go service
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: helloworld-go
  namespace: knative-samples
spec:
  broker: my-rabbit-broker-kn
  filter:
    attributes:
      type: dev.knative.samples.helloworld
      source: dev.knative.samples/helloworldsource
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: helloworld-go
---
apiVersion: eventing.knative.dev/v1alpha1
kind: RabbitmqBrokerConfig
metadata:
  name: my-rabbit-broker-config
  namespace: knative-samples
spec:
  rabbitmqClusterReference:
    # Configure name if a RabbitMQ Cluster Operator is being used.
    name: kn-sample-rabbit-cluster
    # namespace: default
    namespace: knative-samples
    # Configure connectionSecret if an external RabbitMQ cluster is being used.
    # connectionSecret:
      # name: rabbitmq-secret-credentials
  queueType: quorum
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: kn-sample-rabbit-cluster
  namespace: knative-samples
