# Event Display
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display
  namespace: knative-samples
spec:
  broker: my-rabbit-broker-kn
  filter:
    attributes:
      type: dev.knative.samples.hifromknative
      source: knative/eventing/samples/hello-world
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display